config/routes.rb
Rails.application.routes.draw do

  get 'economia/index'
  get 'economia/ranking'

  get 'economia/subitem', as: :economia_subitem

  get 'economia/sgd'

  get 'saude/index'

  get 'saude/medicamentos'

  get 'saude/estoque'

  get 'saude/cirurgias_eletivas'

  get 'saude/ocupacao'

  resources :city_links
  resources :cities
  resources :year_histories
  get 'receita/avaliacao', as: :receita_avaliacao

  get 'receita/relatorio'

  get 'despesa/avaliacao', as: :despesa_avaliacao

  get 'despesa/relatorio', as: :despesa_relatorio
  get 'despesa/pdris', as: :despesa_pdris
  get 'despesa/pessoal', as: :despesa_pessoal
  get 'despesa/comparativo', as: :despesa_comparativo
  post 'despesa/comparativo', as: :despesa_comparativo_post
  get 'despesa/natureza', as: :despesa_natureza
  post 'despesa/natureza', as: :despesa_natureza_post
  get 'despesa/dea', as: :despesa_dea
  post 'despesa/dea', as: :despesa_dea_post
  get 'despesa/insuficiencia', as: :despesa_insuficiencia
  post 'despesa/insuficiencia', as: :despesa_insuficiencia_post
  get 'despesa/balanco', as: :despesa_balanco

  get 'convenios/index', as: :convenios

  get 'convenios/filter', as: :convenios_filter

  get 'emendas/index', as: :emendas

  get 'emendas/resume', as: :emendas_resume

   get 'emendas/home', as: :emendas_home

  resources :import_files
  resources :twitter_counts
  resources :twitter_polls
  resources :news do
    member do
      get "news_status"
    end
    collection do
      get "aprovar"
    end
  end
  resources :statistic_histories
  resources :statistics
  resources :group_statistics
  resources :committal_evolutions
  resources :committals do
    member do
      get 'projects'
    end
  end

  get 'pdris' => "pdris#index", as: :pdris

  get 'pdris/:id' => "pdris#show", as: :pdris_item

  get 'home/index'
  get 'home/gestores'
  get 'home/imprensa', as: :imprensa
  get 'home/redes_sociais', as: :redes_sociais
  get 'home/informacao', as: :informacao
  get 'home/orcamento', as: :orcamento_menu
  get 'home/receita', as: :receita_menu
  get 'home/despesa', as: :despesa_menu
  get 'home/lrf', as: :lrf
  get 'home/resultados', as: :resultados
  get 'home/tocantins_em_numeros', as: :tocantins_em_numeros
  get 'home/cidades', as: :cidades

  get 'powerbi/orcamento', as: :orcamento_bi
  get 'powerbi/receita', as: :receita_bi
  get 'powerbi/evolucao'
  get 'powerbi/mobile_geral', as: :mobile_geral
  get 'powerbi/fonte/:fonte' => "powerbi#fonte", as: :fonte_bi
  get 'powerbi/search' => "powerbi#search", as: :search_bi
  get 'powerbi/search_result' => "powerbi#search_result", as: :search_result_bi
  get 'powerbi/receita_result' => "powerbi#receita_result", as: :receita_result_bi
  get 'powerbi/receita_evolution' => "powerbi#receita_evolution", as: :receita_evolution_bi

  resources :decisions do
    member do
      get "create_project"
    end
  end
  
  resources :raes
  resources :question_replies
  resources :replies
  resources :questions
  resources :goals
  resources :indicator_histories
  resources :indicators do
    member do
      get "analyze"
      get "goals"
      get "histories"
      get "entregas_combo"
      get "probabilidade"
      get "year_history"
    end
    collection do
      get "report"
    end
  end
  get 'auth/redirect' => 'toauth#redirect'
  get 'toauth' => 'toauth#entrar'
  get '/users/sign_in' => 'toauth#redirect'
  devise_for :users
  resources :users
  resources :history_files
  resources :steps
  resources :histories
  resources :projects do
    collection do
      get "my"
    end
    member do
      get "orcamento"
    end
  end

  authenticated :user do
      root 'home#gestores', as: :home_gestor
  end
  constraints DomainCheck.new('www.monitora.to.gov.br') do
    root :to => 'publico#index'
  end

  get 'deed_evaluations/:deed_id' => 'indicators#deed_evaluation'
  get 'deed_acompanhamento/:deed_id' => 'indicators#deed_acompanhamento'

  root 'indicators#index', as: :home_all

    get 'publico/index', as: :publico
    get 'publico/orcamento', as: :pub_orcamento
    get 'publico/entregas', as: :pub_entregas
    get 'publico/pdris', as: :pub_pdris
    get 'publico/indicadores', as: :pub_indicadores
    get 'publico/despesa', as: :pub_despesa
    get 'publico/widget', as: :pub_widget
    get 'publico/secretario', as: :pub_secretario
    get 'publico/secretario_pre', as: :pub_secretario_pre
end

app/models/decision.rb
class Decision < ActiveRecord::Base
	has_paper_trail
	belongs_to :user
	belongs_to :rae
	has_many :projects, dependent: :destroy

	extend Enumerize
	enumerize :status, in: [:sem_monitoramento, :em_andamento, :cumprida], predicates: true, default: :sem_monitoramento
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource except: :create
  before_action :set_decision, only: [:show, :edit, :update, :destroy, :create_project]

  # GET /decisions
  # GET /decisions.json
  def index
    @decisions = Decision.all
  end

  # GET /decisions/1
  # GET /decisions/1.json
  def show
  end

  # GET /decisions/new
  def new
    @decision = Decision.new
  end

  # GET /decisions/1/edit
  def edit
  end

  # POST /decisions
  # POST /decisions.json
  def create
    @decision = Decision.new(decision_params)

    respond_to do |format|
      if @decision.save
        format.html { redirect_to @decision, notice: 'Decision was successfully created.' }
        format.json { render :show, status: :created, location: @decision }
      else
        format.html { render :new }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decisions/1
  # PATCH/PUT /decisions/1.json
  def update
    respond_to do |format|
      if @decision.update(decision_params)
        format.html { redirect_to @decision, notice: 'Decision was successfully updated.' }
        format.json { render :show, status: :ok, location: @decision }
      else
        format.html { render :edit }
        format.json { render json: @decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decisions/1
  # DELETE /decisions/1.json
  def destroy
    @decision.destroy
    respond_to do |format|
      format.html { redirect_to decisions_url, notice: 'Decision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_project
    Project.create_by_decision(@decision, params[:text])
    redirect_to @decision.rae
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_decision
      @decision = Decision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def decision_params
      params.require(:decision).permit(:user_id, :rae_id, :description, :status, :date)
    end
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/views/decisions/_form.html.erb
<%= form_for(@decision) do |f| %>
  <% if @decision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@decision.errors.count, "error") %> prohibited this decision from being saved:</h2>

      <ul>
      <% @decision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :rae_id %><br>
    <%= f.text_field :rae_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decisions/edit.html.erb
<h1>Editing Decision</h1>

<%= render 'form' %>

<%= link_to 'Show', @decision %> |
<%= link_to 'Back', decisions_path %>

app/views/decisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Decisions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Rae</th>
      <th>Description</th>
      <th>Status</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decisions.each do |decision| %>
      <tr>
        <td><%= decision.user %></td>
        <td><%= decision.rae %></td>
        <td><%= decision.description %></td>
        <td><%= decision.status %></td>
        <td><%= decision.date %></td>
        <td><%= link_to 'Show', decision %></td>
        <td><%= link_to 'Edit', edit_decision_path(decision) %></td>
        <td><%= link_to 'Destroy', decision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Decision', new_decision_path %>

app/views/decisions/new.html.erb
<h1>New Decision</h1>

<%= render 'form' %>

<%= link_to 'Back', decisions_path %>

app/views/decisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @decision.user %>
</p>

<p>
  <strong>Rae:</strong>
  <%= @decision.rae %>
</p>

<p>
  <strong>Description:</strong>
  <%= @decision.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @decision.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @decision.date %>
</p>

<%= link_to 'Edit', edit_decision_path(@decision) %> |
<%= link_to 'Back', decisions_path %>