config/routes.rb
Rails.application.routes.draw do

  get 'economia/index'
  get 'economia/ranking'

  get 'economia/subitem', as: :economia_subitem

  get 'economia/sgd'

  get 'saude/index'

  get 'saude/medicamentos'

  get 'saude/estoque'

  get 'saude/cirurgias_eletivas'

  get 'saude/ocupacao'

  resources :city_links
  resources :cities
  resources :year_histories
  get 'receita/avaliacao', as: :receita_avaliacao

  get 'receita/relatorio'

  get 'despesa/avaliacao', as: :despesa_avaliacao

  get 'despesa/relatorio', as: :despesa_relatorio
  get 'despesa/pdris', as: :despesa_pdris
  get 'despesa/pessoal', as: :despesa_pessoal
  get 'despesa/comparativo', as: :despesa_comparativo
  post 'despesa/comparativo', as: :despesa_comparativo_post
  get 'despesa/natureza', as: :despesa_natureza
  post 'despesa/natureza', as: :despesa_natureza_post
  get 'despesa/dea', as: :despesa_dea
  post 'despesa/dea', as: :despesa_dea_post
  get 'despesa/insuficiencia', as: :despesa_insuficiencia
  post 'despesa/insuficiencia', as: :despesa_insuficiencia_post
  get 'despesa/balanco', as: :despesa_balanco

  get 'convenios/index', as: :convenios

  get 'convenios/filter', as: :convenios_filter

  get 'emendas/index', as: :emendas

  get 'emendas/resume', as: :emendas_resume

   get 'emendas/home', as: :emendas_home

  resources :import_files
  resources :twitter_counts
  resources :twitter_polls
  resources :news do
    member do
      get "news_status"
    end
    collection do
      get "aprovar"
    end
  end
  resources :statistic_histories
  resources :statistics
  resources :group_statistics
  resources :committal_evolutions
  resources :committals do
    member do
      get 'projects'
    end
  end

  get 'pdris' => "pdris#index", as: :pdris

  get 'pdris/:id' => "pdris#show", as: :pdris_item

  get 'home/index'
  get 'home/gestores'
  get 'home/imprensa', as: :imprensa
  get 'home/redes_sociais', as: :redes_sociais
  get 'home/informacao', as: :informacao
  get 'home/orcamento', as: :orcamento_menu
  get 'home/receita', as: :receita_menu
  get 'home/despesa', as: :despesa_menu
  get 'home/lrf', as: :lrf
  get 'home/resultados', as: :resultados
  get 'home/tocantins_em_numeros', as: :tocantins_em_numeros
  get 'home/cidades', as: :cidades

  get 'powerbi/orcamento', as: :orcamento_bi
  get 'powerbi/receita', as: :receita_bi
  get 'powerbi/evolucao'
  get 'powerbi/mobile_geral', as: :mobile_geral
  get 'powerbi/fonte/:fonte' => "powerbi#fonte", as: :fonte_bi
  get 'powerbi/search' => "powerbi#search", as: :search_bi
  get 'powerbi/search_result' => "powerbi#search_result", as: :search_result_bi
  get 'powerbi/receita_result' => "powerbi#receita_result", as: :receita_result_bi
  get 'powerbi/receita_evolution' => "powerbi#receita_evolution", as: :receita_evolution_bi

  resources :decisions do
    member do
      get "create_project"
    end
  end
  
  resources :raes
  resources :question_replies
  resources :replies
  resources :questions
  resources :goals
  resources :indicator_histories
  resources :indicators do
    member do
      get "analyze"
      get "goals"
      get "histories"
      get "entregas_combo"
      get "probabilidade"
      get "year_history"
    end
    collection do
      get "report"
    end
  end
  get 'auth/redirect' => 'toauth#redirect'
  get 'toauth' => 'toauth#entrar'
  get '/users/sign_in' => 'toauth#redirect'
  devise_for :users
  resources :users
  resources :history_files
  resources :steps
  resources :histories
  resources :projects do
    collection do
      get "my"
    end
    member do
      get "orcamento"
    end
  end

  authenticated :user do
      root 'home#gestores', as: :home_gestor
  end
  constraints DomainCheck.new('www.monitora.to.gov.br') do
    root :to => 'publico#index'
  end

  get 'deed_evaluations/:deed_id' => 'indicators#deed_evaluation'
  get 'deed_acompanhamento/:deed_id' => 'indicators#deed_acompanhamento'

  root 'indicators#index', as: :home_all

    get 'publico/index', as: :publico
    get 'publico/orcamento', as: :pub_orcamento
    get 'publico/entregas', as: :pub_entregas
    get 'publico/pdris', as: :pub_pdris
    get 'publico/indicadores', as: :pub_indicadores
    get 'publico/despesa', as: :pub_despesa
    get 'publico/widget', as: :pub_widget
    get 'publico/secretario', as: :pub_secretario
    get 'publico/secretario_pre', as: :pub_secretario_pre
end

app/models/question_reply.rb
class QuestionReply < ActiveRecord::Base
	has_paper_trail
	belongs_to :question
	belongs_to :reply
end

app/controllers/question_replies_controller.rb
class QuestionRepliesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource except: :create
  before_action :set_question_reply, only: [:show, :edit, :update, :destroy]

  # GET /question_replies
  # GET /question_replies.json
  def index
    @question_replies = QuestionReply.all
  end

  # GET /question_replies/1
  # GET /question_replies/1.json
  def show
  end

  # GET /question_replies/new
  def new
    @question_reply = QuestionReply.new
  end

  # GET /question_replies/1/edit
  def edit
  end

  # POST /question_replies
  # POST /question_replies.json
  def create
    @question_reply = QuestionReply.new(question_reply_params)

    respond_to do |format|
      if @question_reply.save
        format.html { redirect_to @question_reply, notice: 'Question reply was successfully created.' }
        format.json { render :show, status: :created, location: @question_reply }
      else
        format.html { render :new }
        format.json { render json: @question_reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_replies/1
  # PATCH/PUT /question_replies/1.json
  def update
    respond_to do |format|
      if @question_reply.update(question_reply_params)
        format.html { redirect_to @question_reply, notice: 'Question reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_reply }
      else
        format.html { render :edit }
        format.json { render json: @question_reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_replies/1
  # DELETE /question_replies/1.json
  def destroy
    @question_reply.destroy
    respond_to do |format|
      format.html { redirect_to question_replies_url, notice: 'Question reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_reply
      @question_reply = QuestionReply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_reply_params
      params.require(:question_reply).permit(:question_id, :reply_id, :description)
    end
end

app/helpers/question_replies_helper.rb
module QuestionRepliesHelper
end

app/views/question_replies/_form.html.erb
<%= form_for(@question_reply) do |f| %>
  <% if @question_reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_reply.errors.count, "error") %> prohibited this question_reply from being saved:</h2>

      <ul>
      <% @question_reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.text_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :reply_id %><br>
    <%= f.text_field :reply_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_replies/edit.html.erb
<h1>Editing Question Reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_reply %> |
<%= link_to 'Back', question_replies_path %>

app/views/question_replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Question Replies</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Reply</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_replies.each do |question_reply| %>
      <tr>
        <td><%= question_reply.question %></td>
        <td><%= question_reply.reply %></td>
        <td><%= question_reply.description %></td>
        <td><%= link_to 'Show', question_reply %></td>
        <td><%= link_to 'Edit', edit_question_reply_path(question_reply) %></td>
        <td><%= link_to 'Destroy', question_reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question reply', new_question_reply_path %>

app/views/question_replies/new.html.erb
<h1>New Question Reply</h1>

<%= render 'form' %>

<%= link_to 'Back', question_replies_path %>

app/views/question_replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_reply.question %>
</p>

<p>
  <strong>Reply:</strong>
  <%= @question_reply.reply %>
</p>

<p>
  <strong>Description:</strong>
  <%= @question_reply.description %>
</p>

<%= link_to 'Edit', edit_question_reply_path(@question_reply) %> |
<%= link_to 'Back', question_replies_path %>