config/routes.rb
Rails.application.routes.draw do

  get 'economia/index'
  get 'economia/ranking'

  get 'economia/subitem', as: :economia_subitem

  get 'economia/sgd'

  get 'saude/index'

  get 'saude/medicamentos'

  get 'saude/estoque'

  get 'saude/cirurgias_eletivas'

  get 'saude/ocupacao'

  resources :city_links
  resources :cities
  resources :year_histories
  get 'receita/avaliacao', as: :receita_avaliacao

  get 'receita/relatorio'

  get 'despesa/avaliacao', as: :despesa_avaliacao

  get 'despesa/relatorio', as: :despesa_relatorio
  get 'despesa/pdris', as: :despesa_pdris
  get 'despesa/pessoal', as: :despesa_pessoal
  get 'despesa/comparativo', as: :despesa_comparativo
  post 'despesa/comparativo', as: :despesa_comparativo_post
  get 'despesa/natureza', as: :despesa_natureza
  post 'despesa/natureza', as: :despesa_natureza_post
  get 'despesa/dea', as: :despesa_dea
  post 'despesa/dea', as: :despesa_dea_post
  get 'despesa/insuficiencia', as: :despesa_insuficiencia
  post 'despesa/insuficiencia', as: :despesa_insuficiencia_post
  get 'despesa/balanco', as: :despesa_balanco

  get 'convenios/index', as: :convenios

  get 'convenios/filter', as: :convenios_filter

  get 'emendas/index', as: :emendas

  get 'emendas/resume', as: :emendas_resume

   get 'emendas/home', as: :emendas_home

  resources :import_files
  resources :twitter_counts
  resources :twitter_polls
  resources :news do
    member do
      get "news_status"
    end
    collection do
      get "aprovar"
    end
  end
  resources :statistic_histories
  resources :statistics
  resources :group_statistics
  resources :committal_evolutions
  resources :committals do
    member do
      get 'projects'
    end
  end

  get 'pdris' => "pdris#index", as: :pdris

  get 'pdris/:id' => "pdris#show", as: :pdris_item

  get 'home/index'
  get 'home/gestores'
  get 'home/imprensa', as: :imprensa
  get 'home/redes_sociais', as: :redes_sociais
  get 'home/informacao', as: :informacao
  get 'home/orcamento', as: :orcamento_menu
  get 'home/receita', as: :receita_menu
  get 'home/despesa', as: :despesa_menu
  get 'home/lrf', as: :lrf
  get 'home/resultados', as: :resultados
  get 'home/tocantins_em_numeros', as: :tocantins_em_numeros
  get 'home/cidades', as: :cidades

  get 'powerbi/orcamento', as: :orcamento_bi
  get 'powerbi/receita', as: :receita_bi
  get 'powerbi/evolucao'
  get 'powerbi/mobile_geral', as: :mobile_geral
  get 'powerbi/fonte/:fonte' => "powerbi#fonte", as: :fonte_bi
  get 'powerbi/search' => "powerbi#search", as: :search_bi
  get 'powerbi/search_result' => "powerbi#search_result", as: :search_result_bi
  get 'powerbi/receita_result' => "powerbi#receita_result", as: :receita_result_bi
  get 'powerbi/receita_evolution' => "powerbi#receita_evolution", as: :receita_evolution_bi

  resources :decisions do
    member do
      get "create_project"
    end
  end
  
  resources :raes
  resources :question_replies
  resources :replies
  resources :questions
  resources :goals
  resources :indicator_histories
  resources :indicators do
    member do
      get "analyze"
      get "goals"
      get "histories"
      get "entregas_combo"
      get "probabilidade"
      get "year_history"
    end
    collection do
      get "report"
    end
  end
  get 'auth/redirect' => 'toauth#redirect'
  get 'toauth' => 'toauth#entrar'
  get '/users/sign_in' => 'toauth#redirect'
  devise_for :users
  resources :users
  resources :history_files
  resources :steps
  resources :histories
  resources :projects do
    collection do
      get "my"
    end
    member do
      get "orcamento"
    end
  end

  authenticated :user do
      root 'home#gestores', as: :home_gestor
  end
  constraints DomainCheck.new('www.monitora.to.gov.br') do
    root :to => 'publico#index'
  end

  get 'deed_evaluations/:deed_id' => 'indicators#deed_evaluation'
  get 'deed_acompanhamento/:deed_id' => 'indicators#deed_acompanhamento'

  root 'indicators#index', as: :home_all

    get 'publico/index', as: :publico
    get 'publico/orcamento', as: :pub_orcamento
    get 'publico/entregas', as: :pub_entregas
    get 'publico/pdris', as: :pub_pdris
    get 'publico/indicadores', as: :pub_indicadores
    get 'publico/despesa', as: :pub_despesa
    get 'publico/widget', as: :pub_widget
    get 'publico/secretario', as: :pub_secretario
    get 'publico/secretario_pre', as: :pub_secretario_pre
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, except: [:orcamento, :lrf, :tocantins_em_numeros, :cidades]
	authorize_resource class: :home, except: [:orcamento, :lrf, :cidades]
	def index
	end

	def gestores
	end

	def imprensa
		endereco = "https://www.googleapis.com/customsearch/v1?key=AIzaSyCj8ttov8TadRwafLqs7ic38P3IQnKNdOw&cx=002871630582686314731:wvbp-djnbww&q=tocantins+noticia&dateRestrict=d7"
		data = JSON.parse(RestClient.send(:get, endereco), symbolize_names: true)
		begin
			@data = data[:items]			
		rescue 
			@data= []			
		end
	end

	def redes_sociais
		@bem = TwitterCount.where(good: true).sum(:value)
		@mal = TwitterCount.where(good: [false, nil]).sum(:value)
		@polls = TwitterPoll.all
	end

	def orcamento
		if user_signed_in?
			@orcamento_link = despesa_menu_path
			@receita_link = receita_bi_path
		else
		 	@orcamento_link = pub_despesa_path
			@receita_link = receita_bi_path
		end
	end

	def cidades
		@cidades = JSON.parse(RestClient.get("http://cidades.monitora.to.gov.br/cidades.json")).map{|a| [a["text"], a["id"]]}
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_noticia.html.erb
<div class="col s12 m8 offset-m2">
	<div class="card">
		<div class="card-image">
			<%# binding.pry %>
			<% if noticia[:pagemap][:cse_image]  %>
			<img src="<%= noticia[:pagemap][:cse_image].first[:src] || "/bg-tocantins.jpg"%>">
			<% else %>
			<img src="/bg-tocantins.jpg" alt="sample image">
			<% end %>

		</div>
		<div class="card-content">
			<span class="card-title black-text"><%= noticia[:pagemap][:newsarticle].first[:"headline"] || noticia[:title]  %></span>
			<p><%= noticia[:pagemap][:newsarticle].first[:"description"]  %></p>
		</div>
		<%# as  %>
		<div class="card-action">
			<a class="blue-text"><%= noticia[:displayLink]   %></a>
			<a href="<%= noticia[:link]%>">Ver Noticia</a>
		</div>
	</div>
</div>

app/views/home/cidades.html.erb
<%= select_tag :cidade, options_for_select(@cidades), onchange: "change_frame()" , id: "cidade"%>
<iframe src="" frameborder="0" id="city_frame" height="500px" width="100%"></iframe>

<script type="text/javascript" charset="utf-8">
  function change_frame() {
      $('#city_frame').attr('src', "http://cidades.monitora.to.gov.br/integra/eixos/" + $("#cidade").val())
  }
</script>

app/views/home/despesa.html.erb
<div class="col s12 m3">
  <div class="card-panel  gradient-45deg-light-blue-cyan" onclick="toggle_orcamento()">
    <div class="row">        
      <div class="s12 center">
        <i class="fa fa-pie-chart fa-4x white-text center" ></i>
      </div>
    </div>
    <h4 class="white-text center">
      Despesa
    </h4>
    <div class="white-text center">
      Execução Orçamentária Extraída do SIAFEM - Relorc
    </div>
    <div id="sub_orcamento">      
      <%= link_to search_bi_path do  %>     
      <div class="card-panel" style="background: none; ">
        <h5 class="white-text">
          Relatório Geral
        </h5>
      </div>
      <% end %>
      <%= link_to "http://gastos.monitora.to.gov.br" do  %>
          <div class="card-panel" style="background: none; ">
            <h5 class="white-text">
              Controle de Gastos
            </h5>
          </div>
      <% end %>
      <%= link_to despesa_pessoal_path do  %>
          <div class="card-panel" style="background: none; ">
            <h5 class="white-text">
              Análise de Pessoal
            </h5>
          </div>
      <% end %>
      <% link_to despesa_avaliacao_path do  %>     
      <div class="card-panel" style="background: none; ">
        <h5 class="white-text">
          Avaliação da Despesa
        </h5>
      </div>
      <% end %>
      <% link_to emendas_home_path do  %>     
      <div class="card-panel" style="background: none; ">
        <h5 class="white-text">
          Emendas Parlamentares
        </h5>
      </div>
      <% end %> 
      <% link_to convenios_path do  %>     
      <div class="card-panel" style="background: none; ">
        <h5 class="white-text">
          Convênios
        </h5>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/gestores.html.erb
<div class="row">


  <%= link_to orcamento_menu_path do  %>
  <div class="col s12 m6">
    <div class="card  gradient-45deg-purple-light-blue">
      <div class="card-content">
        <div class="row">        
          <div class="s12 center">
            <i class="fa fa-signal fa-4x white-text center" ></i>
          </div>
        </div>
        <h4 class="white-text center">
          Orçamento
        </h4>
        <div class="white-text center">
          Receitas e Execução Financeira 
        </div>
      </div>
    </div>
  </div>
  
  <% end %>

  <%= link_to lrf_path do  %>
  <div class="col s12 m6">
    <div class="card  gradient-45deg-purple-light-blue ">
      <div class="card-content">
        <div class="row">        
          <div class="s12 center">
            <i class="fa fa-pie-chart fa-4x white-text center" ></i>
          </div>
        </div>
        <h4 class="white-text center">
          LRF
        </h4>
        <div class="white-text center">
          Lei de Responsabilidade Fiscal
        </div>
      </div>
    </div>
  </div>  
  <% end %>
  <% if can? :read, :emendas %>

  <div class="col s12 m4">
    <%= link_to "http://gastos.monitora.to.gov.br", target: :_blank do  %>
    <div class="card-panel  gradient-45deg-purple-light-blue center">
      <div class="row">        
        <div class="s12 center">
          <i class="fa fa-usd fa-4x white-text center"></i>
        </div>
      </div>
      <h4 class="white-text">
        Gastos
      </h4>
      <span class="white-text">
        Dashboards Exclusivas de Gastos
      </span>
    </div>
    <% end %>  
  </div>

  <div class="col s12 m4">
    <%= link_to saude_index_path do  %>
    <div class="card-panel  gradient-45deg-purple-light-blue center">
      <div class="row">
        <div class="s12 center">
          <i class="fa fa-medkit fa-4x white-text center"></i>
        </div>
      </div>
      <h4 class="white-text">
        Integra Saúde
      </h4>
      <span class="white-text">
        Sitação em Tempo Real da Saúde
      </span>
    </div>
    <% end %>
  </div>

  <div class="col s12 m4">
    <%= link_to despesa_pessoal_path do  %>
    <div class="card-panel  gradient-45deg-purple-light-blue center">
      <div class="row">
        <div class="s12 center">
          <i class="fa fa-users fa-4x white-text center"></i>
        </div>
      </div>
      <h4 class="white-text">
        Pessoal
      </h4>
      <span class="white-text">
        Análise Quantitativa de Pessoal
      </span>
    </div>
    <% end %>
  </div>

  <div class="col s12 m6">
    <%= link_to "http://seplan.to.gov.br/estatistica/tocantins-em-numeros/", target: :_blank do  %>
    <div class="card-panel  gradient-45deg-purple-light-blue center">
      <div class="row">
        <div class="s12 center">
          <i class="fa fa-bar-chart fa-4x white-text center"></i>
        </div>
      </div>
      <h4 class="white-text">
        Estatísticas
      </h4>
      <span class="white-text">
        Informações importantes sobre o Estado
      </span>
    </div>
    <% end %>
  </div>
  <div class="col s12 m6">
    <%= link_to informacao_path do  %>      
    <div class="card-panel gradient-45deg-purple-light-blue center">
      <div class="row">        
        <div class="s12 center">
          <i class="fa fa-comments-o fa-4x white-text center"></i>
        </div>
      </div>
      <h4 class="white-text">
        Mídia
      </h4>
      <span class="white-text">
        O que estão falando sobre o Estado do Tocantins.
      </span>
    </div>
    <% end %>  
  </div>
  <% end %>
  <%= content_for :scripts do  %>
  <script type="text/javascript">
    function toggle_orcamento() {
      var menu = $('#sub_orcamento');
      if (menu.is(":visible")) {
        menu.hide();

      }else{
        menu.show();
      };

    }

  </script>

  <% end %>

app/views/home/imprensa.html.erb
<div class="center">	
<h4 class="header">As Notícias Mais Lidas Sobre o Estado</h4>
	<p>Segundo o Google</p>
</div>
<div class="row">	
	<% @data.each do |noticia|  %>
	<%= render partial:'home/noticia', locals:{noticia:noticia} %>
	<% end %>
	<% if @data.blank? %>

		<div class="card-panel red center">
			<h5 class="white-text">				
				O serviço do Google está temporariamente fora do ar. Esta é uma falha do Google e não do Monitora. Você pode tentar voltar mais tarde ou acessar uma pesquisa do Google enquanto eles não resolvem o problema no link abaixo:<br><br>
				<a href="http://www.google.com/search?q=tocantins&tbm=nws" class="btn btn-large col s12" target="_blank">
					Ver Pesquisa do Google
				</a>
			</h5>
		</div>

	<% else %>	
	<div class="col s12 m8 offset-m2 row">
		<a href="<%= @link  %>" class="btn btn-large col s12">Mais Resultados</a>
	</div>
	<% end %>
</div>

app/views/home/informacao.html.erb
<div class="col s12 m6">
  <%= link_to redes_sociais_path do  %>      
  <div class="card-panel green center">
    <div class="row">        
      <div class="s12 center">
        <i class="fa fa-whatsapp fa-4x white-text center"></i>
      </div>
    </div>
    <h4 class="white-text">
      Termômetro das Redes Sociais
    </h4>
    <span class="white-text">
      O que as pessoas falam do estado nas Redes Sociais
    </span>
  </div>
  <% end %>  
</div>

<div class="col s12 m6">
  <%= link_to imprensa_path do  %>      
  <div class="card-panel  amber darken-2 center">
    <div class="row">        
      <div class="s12 center">
        <i class="fa fa-newspaper-o fa-4x white-text center"></i>
      </div>
    </div>
    <h4 class="white-text">
      Imprensa
    </h4>
    <span class="white-text">
      As noticias mais lidas do Estado
    </span>
  </div>
  <% end %>  
</div>

app/views/home/lrf.html.erb
<div class="card-panel">
  <img src="/lrf/lrf.png" alt="" class="responsive-img">
  <p>
		<b>Pessoal: </b> Máximo Prudencial = 46,55% e Máximo Legal = 49% <br>
		<b>Educação: </b>Mínimo Legal = 25% <br>
		<b>Saúde: </b>Mínimo Legal = 12% <br>
	</p>
</div>


<div class="card-panel">
  <img src="/lrf/lrf2.png" alt="" class="responsive-img">
</div>

<div class="card-panel">
  <img src="/lrf/lrf3.png" alt="" class="responsive-img">
</div>

app/views/home/orcamento.html.erb
<%= link_to @receita_link do  %>      
<div class="card-panel  gradient-45deg-cyan-light-green center" data-step="1" data-intro="Neste ícone mostraremos tudo que o Estado pretende arrecadar e o quanto já arrecadou para desenvolver politicas públicas de qualidade para o Tocantins." data-position='left'>
  <div class="row">        
    <div class="s12 center">
      <i class="fa fa-usd fa-4x white-text center"></i>
    </div>
  </div>
  <h5 class="white-text">
    Receita
  </h5>
  <span class="white-text">
    Arrecadação - Anexo 10
  </span>
</div>
<% end %>

<%= link_to search_bi_path do  %>
<div class="card-panel  gradient-45deg-red-pink center" data-step="2" data-intro="Aqui você poderá ver de forma atualizada como está a execução financeira do Estado e acompanhar aonde o Governo está investindo os recursos." data-position='left'>
  <div class="row">        
    <div class="s12 center">
      <i class="fa fa-pie-chart fa-4x white-text center"></i>
    </div>
  </div>
  <h5 class="white-text">
    Despesas
  </h5>
  <span class="white-text">
    Execução Financeira - Relorc
  </span>
</div>
<% end %>  


<%= link_to despesa_balanco_path do  %>
<div class="card-panel  gradient-45deg-indigo-light-blue center" data-step="2" data-intro="Aqui você poderá ver de forma atualizada como está a execução financeira do Estado e acompanhar aonde o Governo está investindo os recursos." data-position='left'>
  <div class="row">
    <div class="s12 center">
      <i class="fa fa-balance-scale fa-4x white-text center"></i>
    </div>
  </div>
  <h5 class="white-text">
    Balanço Orçamentário
  </h5>
  <span class="white-text">
    Arrecadado X Liquidado
  </span>
</div>
<% end %>

app/views/home/receita.html.erb
<div class="col s12 m3">
  <div class="card-panel  green" onclick="toggle_orcamento()">
    <div class="row">        
      <div class="s12 center">
        <i class="fa fa-usd fa-4x white-text center" ></i>
      </div>
    </div>
    <h4 class="white-text center">
      Receita
    </h4>
    <div class="white-text center">
      Informações da Reeita do SIAFEM - Anexo 10
    </div>
    <div id="sub_orcamento">      
      <%= link_to receita_bi_path do  %>     
      <div class="card-panel  green darken-3">
        <h5 class="white-text">
          Relatório Geral
        </h5>
      </div>
      <% end %>
      <%= link_to receita_evolution_bi_path do  %>     
      <div class="card-panel  green darken-3">
        <h5 class="white-text">
          Evolução da Receita
        </h5>
      </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/home/redes_sociais.html.erb
<div class="card-panel center white-text blue">
	<h4>Redes Sociais</h4>
	<p>O que as pessoas estão dizendo sobre o estado nas redes sociais.</p>
</div>
<div class="card-panel">
	<div id="piechart" style="width: 100%; height: 500px;"></div>
</div>

<div class="row"> 
<% @polls.each do |poll|  %>
  <%= link_to poll do %>
  <div class="col s12 m4">
    <div class="card-panel center">
      <h4><%= poll.name  %></h4>
    </div>
  </div>
  <% end %>
<% end %>
</div>

<%= content_for :head do %>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {

        var dataTable = new google.visualization.DataTable();
        dataTable.addColumn('string', 'Resposta');
        dataTable.addColumn('number', 'Valor');
        dataTable.addColumn({type: 'string', role: 'tooltip'});
        dataTable.addRows([
          ['Falando Bem', <%= @bem  %>,'Falando Bem'],
          ['Falando Mal', <%= @mal  %>,'Falando Mal']
        ]);
        var options = {
          is3D: true,
          slices: {
            0: { color: '#004d40' },
            1: { color: '#b71c1c' }
          }
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(dataTable, options);
      }
    </script>
<% end %>

app/views/home/resultados.html.erb
<div class="card-panel center"> 
  <img src="/images/resultados/3.jpg" class="responsive-img">
</div>
<div class="card-panel center"> 
  <img src="/images/resultados/1.jpg" class="responsive-img">
</div>
<div class="card-panel center"> 
  <img src="/images/resultados/2.jpg" class="responsive-img">
</div>
<div class="card-panel center"> 
  <img src="/images/resultados/4.jpg" class="responsive-img">
</div>

app/views/home/tocantins_em_numeros.html.erb
<div class="col s12 m6">
  <%= link_to "http://seplan.to.gov.br/estatistica/tocantins-em-numeros/" do  %>
  <div class="card-panel green center">
    <div class="row">        
      <div class="s12 center">
        <i class="fa fa-bar-chart fa-4x white-text center"></i>
      </div>
    </div>
    <h4 class="white-text">
      Tocantins em Números
    </h4>
    <span class="white-text">
      Dados e Estatísticas Relevantes do Tocantins
    </span>
  </div>
  <% end %>  
</div>
<div class="col s12 m6">
  <%= link_to "/saude/index" do  %>
  <div class="card-panel red center">
    <div class="row">        
      <div class="s12 center">
        <i class="fa fa-bar-chart fa-4x white-text center"></i>
      </div>
    </div>
    <h4 class="white-text">
      Integra Saúde
    </h4>
    <span class="white-text">
      Dados Relevantes da Saúde no Tocantins
    </span>
  </div>
  <% end %>  
</div>
<div class="col s12 m6">
  <%= link_to cities_path do  %>
  <div class="card-panel  amber darken-2 center">
    <div class="row">        
      <div class="s12 center">
        <i class="fa fa-bar-chart fa-4x white-text center"></i>
      </div>
    </div>
    <h4 class="white-text">
      Perfil Municipal
    </h4>
    <span class="white-text">
      Relatórios da Seplan, TCE e IBGE
    </span>
  </div>
  <% end %>  
</div>