config/routes.rb
Rails.application.routes.draw do

  get 'economia/index'
  get 'economia/ranking'

  get 'economia/subitem', as: :economia_subitem

  get 'economia/sgd'

  get 'saude/index'

  get 'saude/medicamentos'

  get 'saude/estoque'

  get 'saude/cirurgias_eletivas'

  get 'saude/ocupacao'

  resources :city_links
  resources :cities
  resources :year_histories
  get 'receita/avaliacao', as: :receita_avaliacao

  get 'receita/relatorio'

  get 'despesa/avaliacao', as: :despesa_avaliacao

  get 'despesa/relatorio', as: :despesa_relatorio
  get 'despesa/pdris', as: :despesa_pdris
  get 'despesa/pessoal', as: :despesa_pessoal
  get 'despesa/comparativo', as: :despesa_comparativo
  post 'despesa/comparativo', as: :despesa_comparativo_post
  get 'despesa/natureza', as: :despesa_natureza
  post 'despesa/natureza', as: :despesa_natureza_post
  get 'despesa/dea', as: :despesa_dea
  post 'despesa/dea', as: :despesa_dea_post
  get 'despesa/insuficiencia', as: :despesa_insuficiencia
  post 'despesa/insuficiencia', as: :despesa_insuficiencia_post
  get 'despesa/balanco', as: :despesa_balanco

  get 'convenios/index', as: :convenios

  get 'convenios/filter', as: :convenios_filter

  get 'emendas/index', as: :emendas

  get 'emendas/resume', as: :emendas_resume

   get 'emendas/home', as: :emendas_home

  resources :import_files
  resources :twitter_counts
  resources :twitter_polls
  resources :news do
    member do
      get "news_status"
    end
    collection do
      get "aprovar"
    end
  end
  resources :statistic_histories
  resources :statistics
  resources :group_statistics
  resources :committal_evolutions
  resources :committals do
    member do
      get 'projects'
    end
  end

  get 'pdris' => "pdris#index", as: :pdris

  get 'pdris/:id' => "pdris#show", as: :pdris_item

  get 'home/index'
  get 'home/gestores'
  get 'home/imprensa', as: :imprensa
  get 'home/redes_sociais', as: :redes_sociais
  get 'home/informacao', as: :informacao
  get 'home/orcamento', as: :orcamento_menu
  get 'home/receita', as: :receita_menu
  get 'home/despesa', as: :despesa_menu
  get 'home/lrf', as: :lrf
  get 'home/resultados', as: :resultados
  get 'home/tocantins_em_numeros', as: :tocantins_em_numeros
  get 'home/cidades', as: :cidades

  get 'powerbi/orcamento', as: :orcamento_bi
  get 'powerbi/receita', as: :receita_bi
  get 'powerbi/evolucao'
  get 'powerbi/mobile_geral', as: :mobile_geral
  get 'powerbi/fonte/:fonte' => "powerbi#fonte", as: :fonte_bi
  get 'powerbi/search' => "powerbi#search", as: :search_bi
  get 'powerbi/search_result' => "powerbi#search_result", as: :search_result_bi
  get 'powerbi/receita_result' => "powerbi#receita_result", as: :receita_result_bi
  get 'powerbi/receita_evolution' => "powerbi#receita_evolution", as: :receita_evolution_bi

  resources :decisions do
    member do
      get "create_project"
    end
  end
  
  resources :raes
  resources :question_replies
  resources :replies
  resources :questions
  resources :goals
  resources :indicator_histories
  resources :indicators do
    member do
      get "analyze"
      get "goals"
      get "histories"
      get "entregas_combo"
      get "probabilidade"
      get "year_history"
    end
    collection do
      get "report"
    end
  end
  get 'auth/redirect' => 'toauth#redirect'
  get 'toauth' => 'toauth#entrar'
  get '/users/sign_in' => 'toauth#redirect'
  devise_for :users
  resources :users
  resources :history_files
  resources :steps
  resources :histories
  resources :projects do
    collection do
      get "my"
    end
    member do
      get "orcamento"
    end
  end

  authenticated :user do
      root 'home#gestores', as: :home_gestor
  end
  constraints DomainCheck.new('www.monitora.to.gov.br') do
    root :to => 'publico#index'
  end

  get 'deed_evaluations/:deed_id' => 'indicators#deed_evaluation'
  get 'deed_acompanhamento/:deed_id' => 'indicators#deed_acompanhamento'

  root 'indicators#index', as: :home_all

    get 'publico/index', as: :publico
    get 'publico/orcamento', as: :pub_orcamento
    get 'publico/entregas', as: :pub_entregas
    get 'publico/pdris', as: :pub_pdris
    get 'publico/indicadores', as: :pub_indicadores
    get 'publico/despesa', as: :pub_despesa
    get 'publico/widget', as: :pub_widget
    get 'publico/secretario', as: :pub_secretario
    get 'publico/secretario_pre', as: :pub_secretario_pre
end

app/models/history.rb
class History < ActiveRecord::Base
  has_paper_trail
  belongs_to :step
  belongs_to :user
  has_many :history_files

  accepts_nested_attributes_for :history_files, :allow_destroy => true

  after_save :set_status_step

  default_scope -> {order(created_at: :desc)}

  def set_status_step
  	step.status = step.get_status
  	step.save
  end

  def photos
  	history_files.where(type: :photo)
  end
  
  def videos
  	history_files.where(type: :video)
  end

  def links
    URI.extract(description, ["http","https"])
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  load_and_authorize_resource except: :create
  before_action :authenticate_user!
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    redirect_to projects_path
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)
    @history.user = current_user
    respond_to do |format|
      if @history.save
        format.html { redirect_to @history.step.project, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history.step.project, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(
        :name, :step_id, :description, :user_id, :finish,
        history_files_attributes:[
          :id, :name, :file, :history_id, :type, :_destroy
        ]
        )
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= nested_form_for(@history) do |f| %>
<% if @history.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

  <ul>
    <% @history.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div id="UpdateStatus" class="tab-content col s12  grey lighten-4" style="display: block;">
  <div class="row">                
    <div class="col s2">
      <img src="<%= @toauth_fast[:photo] %>" alt="" class="circle responsive-img valign profile-image-post">
    </div>
    <div class="input-field col s10">
      <%= f.select :step_id, @history.step.project.steps.map{|e| [e.name, e.id]}, {}, {class:"browser-default"} %>
      <%= f.text_area :description, class:"materialize-textarea", row:2, placeholder: "Descreva aqui o histórico..." %>                    
    </div>
  </div>
  <div class="col s12 card-panel">     
    <div id="file_pdf"> 
      <h5>Arquivos</h5>           
      <%= f.fields_for :history_files do |hf| %>
      <div class="row">
        <div class="input-field col s4">                    
          <%= hf.text_field :name, required: true %>
          <%= hf.label :name, "Nome" %>
        </div>
        <div class="input-field col s4">                    
          <%= hf.select :type, HistoryFile.type.options, {}, {class:"browser-default"} %>
        </div>
        <div class="col s3"> 
          <div class="file-field input-field">
            <input class="file-path validate" type="text" />
            <div class="btn cyan">
              <span><i class="mdi-editor-attach-file"></i></span>
              <%= hf.file_field :file %>
            </div>
          </div>                  
        </div>
        <div class="input-field col s1">                    
          <%= hf.link_to_remove class:"btn-floating btn-flat waves-effect waves-light red accent-2 white-text" do %>
            <i class="mdi-content-content-cut"></i>
            <% end %>
        </div>
      </div>
      <% end %>
    </div>              
  </div>
  <div class="row">
    <div class="col s12 m9 share-icons">
      <%= f.link_to_add :history_files, "data-target" => "#file_pdf", class:"btn cyan" do %>
      <i class="mdi-editor-attach-file"></i> Inserir Arquivo
      <% end %>
      <div class="btn blue ">        
        <%= f.check_box :finish , class:"check_form" %>
        <%= f.label :finish , "Tarefa Finalizada", class:"white-text"%>
      </div>
    </div>

    <!-- Dropdown Structure -->

    <%= button_tag type: :submit, class:"waves-effect waves-light btn" do %>
    <i class="mdi-maps-rate-review left"></i>Salvar
    <% end %>
  </div>
</div>

<% end %>

app/views/histories/edit.html.erb
<%= render 'form' %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Histories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Step</th>
      <th>Description</th>
      <th>User</th>
      <th>Finish</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.name %></td>
        <td><%= history.step %></td>
        <td><%= history.description %></td>
        <td><%= history.user %></td>
        <td><%= history.finish %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @history.name %>
</p>

<p>
  <strong>Step:</strong>
  <%= @history.step %>
</p>

<p>
  <strong>Description:</strong>
  <%= @history.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @history.user %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @history.finish %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>